import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="bg-pink h-screen w-full">
      <Head>
        <title>Jade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href={
            "https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap"
          }
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href={
            "https://fonts.googleapis.com/css2?family=Amiko&family=Roboto:wght@300&display=swap"
          }
          rel="stylesheet"
        />
      </Head>
      {/* header */}
      <div className="h-16 px-3 sm:h-32 sm:px-10 flex items-center">
        {/* logo */}
        <Link href="/">
          <svg
            className="h-16 w-16 sm:h-[4.5rem] sm:w-[4.5rem] cursor-pointer"
            viewBox="0 0 160 160"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle cx="54" cy="83" r="54" fill="#EC8244" />
            <path
              d="M39.375 128.625C37.625 128.625 35.1875 128.521 32.0625 128.312V116.25C33.7292 116.75 36.7292 117 41.0625 117C45.4375 117 49.1042 116.396 52.0625 115.188C55.0625 113.979 57.5625 112.062 59.5625 109.438C63.6042 104.146 65.625 95.6667 65.625 84V52.0625H33.5625V41H78.125V84C78.125 106.583 71.0208 120.542 56.8125 125.875C51.9375 127.708 46.125 128.625 39.375 128.625Z"
              fill="white"
            />
          </svg>
        </Link>
        <div className="flex-1" />
        {/* nav */}
        <Link href="/">
          <span className="text-2xl text-white border-2 border-orange px-2 py-[0.2rem] rounded-xl hover:bg-orange hover:text-white cursor-pointer">
            My Writing
          </span>
        </Link>
      </div>
      {/* hero */}
      <div className="flex justify-center mt-9 pb-12 sm:pb-16 m-3 sm:m-5">
        <div className="space-y-10">
          <h1 className="mx-auto font-inder font-extrabold text-8xl text-white">
            Hey, it&prime;s{" "}
            <span className="underline decoration-wavy decoration-2 md:decoration-[3px] decoration-orange">
              Jade
            </span>
          </h1>
          <p className="font-inder font-extrabold text-3xl text-white ">
            An indie hacker experimenting with solutions to every day problems.
          </p>
        </div>
      </div>
      {/* building */}
      <div className="bg-white divide-y-2 divide-orange px-4 pt-10 sm:px-20 sm:pt-20">
        <h1 className="text-orange text-2xl font-amiko tracking-widest font-bold text-center md:w-1/4 sm:w-full pb-1">
          BUILDING
        </h1>
        <div className="font-amiko px-9 sm:px-24 pt-5 space-y-1">
          <div className="flex items-center space-x-1">
            <h1 className="text-xl font-semibold tracking-wide">
              WALKERS PARADISE
            </h1>
            <a
              href="https://walkerparadise.vercel.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <svg
                className="h-4 w-4 fill-orange cursor-pointer"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                  clipRule="evenodd"
                />
              </svg>
            </a>
          </div>
          <p className="text-lg">
            I&prime;m currently working on{" "}
            <a
              href={"https://walkerparadise.vercel.app/"}
              target="_blank"
              rel="noopener noreferrer"
            >
              <span className="text-orange cursor-pointer hover:border-1 hover:border-b hover:border-orange">
                walkers paradise
              </span>
            </a>
            , where we route a safe walking path to your destination in San
            Francisco using SFPD data and Google Maps API. This is a constantly
            changing project as I iterate with new ideas. If you&prime;re
            interested in following the journey, check out my #buildingInPublic{" "}
            <Link href={"/"}>
              <span className="text-orange cursor-pointer hover:border-1 hover:border-b hover:border-orange">
                thread
              </span>
            </Link>{" "}
            on twitter!
          </p>
        </div>
      </div>
      {/* projects */}
      <div className="bg-white divide-y-2 divide-orange px-4 py-10 sm:px-20 sm:py-20">
        <h1 className="text-orange text-2xl font-amiko tracking-widest font-bold text-center md:w-1/4 sm:w-full pb-1">
          PROJECTS
        </h1>
        <div className="font-amiko px-9 sm:px-24 md:grid md:grid-cols-2 md:items-start items-center md:gap-x-20 md:gap-y-5">
          {/* essay community */}
          <div className="pt-5">
            <div className="flex items-center space-x-2 pb-1">
              <h1 className="text-lg font-semibold">Essay</h1>
              <a
                href="https://www.essay.community/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <svg
                  className="h-4 w-4 fill-orange cursor-pointer"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                >
                  <path
                    fillRule="evenodd"
                    d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                    clipRule="evenodd"
                  />
                </svg>
              </a>
            </div>
            <p className="text-lg">
              Blogging site that anyone can create an account in and start
              posting their thoughts! I currently use this to publish my own
              essays.
            </p>
          </div>

          {/* pomodoro timer */}
          <div className="pt-5">
            <div className="flex items-center space-x-2 pb-1">
              <h1 className="text-lg font-semibold">Pomodoro timer</h1>
              <a
                href="https://timer-jadeasmus.vercel.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <svg
                  className="h-4 w-4 fill-orange cursor-pointer"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                >
                  <path
                    fillRule="evenodd"
                    d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                    clipRule="evenodd"
                  />
                </svg>
              </a>
            </div>
            <p className="text-lg">
              Pomodoro study timer made with Next.js and Tailwindcss.
            </p>
          </div>

          {/* scraper */}
          <div className="pt-5">
            <div className="flex items-center space-x-2 pb-1">
              <h1 className="text-lg font-semibold">Local therapist finder</h1>
              <a
                href="https://github.com/jadeasmus/psychtoday-web-scraper"
                target="_blank"
                rel="noopener noreferrer"
              >
                <svg
                  className="h-4 w-4 fill-orange cursor-pointer"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                >
                  <path
                    fillRule="evenodd"
                    d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 101.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"
                    clipRule="evenodd"
                  />
                </svg>
              </a>
            </div>
            <p className="text-lg">
              Web scraper that finds local therapists made with Flask and
              BeautifulSoup.
            </p>
          </div>
        </div>
      </div>
      <footer className="flex items-center bg-pink space-x-5 py-1 p-3 sm:py-2 sm:p-6">
        <p className="text-white">Jade ❤️</p>
        <div className="flex-1" />
        <div className="flex space-x-1 sm:space-x-4">
          {/* twitter */}
          <Link href="https://twitter.com/functionofJade">
            <svg
              className="h-10 w-10 fill-orange bg-white rounded-full p-1 cursor-pointer border-2 border-pink hover:border-2 hover:border-orange"
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
            >
              <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z" />
            </svg>
          </Link>
          {/* github */}
          <Link href="https://github.com/jadeasmus">
            <svg
              className="h-10 w-10 fill-orange bg-white rounded-full p-1 cursor-pointer border-2 border-pink hover:border-2 hover:border-orange"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
            >
              <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
            </svg>
          </Link>
          {/* email */}
          <Link href="mailto: hi@jadeasmus.com">
            <svg
              className="h-10 w-10 text-orange bg-white rounded-full p-1 cursor-pointer border-2 border-pink hover:border-2 hover:border-orange"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
              <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
            </svg>
          </Link>
        </div>
      </footer>
    </div>
  );
}
